// Code generated by "stringer -type=operation"; DO NOT EDIT.

package maptracker

import "strconv"

const _operation_name = "operationUnknownoperationPinoperationUnpin"

var _operation_index = [...]uint8{0, 16, 28, 42}

func (i operation) String() string {
	if i < 0 || i >= operation(len(_operation_index)-1) {
		return "operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _operation_name[_operation_index[i]:_operation_index[i+1]]
}
