// Code generated by "stringer -type=phase"; DO NOT EDIT.

package maptracker

import "strconv"

const _phase_name = "phaseErrorphaseQueuedphaseInProgress"

var _phase_index = [...]uint8{0, 10, 21, 36}

func (i phase) String() string {
	if i < 0 || i >= phase(len(_phase_index)-1) {
		return "phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _phase_name[_phase_index[i]:_phase_index[i+1]]
}
