// Code generated by protoc-gen-go. DO NOT EDIT.
//
// Actually, the above line is just to avoid golint complains.
// Run go:generate to generate the protobuf types in this module.
//
//go:generate protoc -I=. --go_out=. types.proto
package api_pb
