// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package api_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pin_PinType int32

const (
	Pin_BadType        Pin_PinType = 0
	Pin_DataType       Pin_PinType = 1
	Pin_MetaType       Pin_PinType = 2
	Pin_ClusterDAGType Pin_PinType = 3
	Pin_ShardType      Pin_PinType = 4
)

var Pin_PinType_name = map[int32]string{
	0: "BadType",
	1: "DataType",
	2: "MetaType",
	3: "ClusterDAGType",
	4: "ShardType",
}

var Pin_PinType_value = map[string]int32{
	"BadType":        0,
	"DataType":       1,
	"MetaType":       2,
	"ClusterDAGType": 3,
	"ShardType":      4,
}

func (x Pin_PinType) String() string {
	return proto.EnumName(Pin_PinType_name, int32(x))
}

func (Pin_PinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0, 0}
}

type Pin struct {
	Cid                  []byte      `protobuf:"bytes,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	Type                 Pin_PinType `protobuf:"varint,2,opt,name=Type,proto3,enum=api.pb.Pin_PinType" json:"Type,omitempty"`
	Allocations          [][]byte    `protobuf:"bytes,3,rep,name=Allocations,proto3" json:"Allocations,omitempty"`
	MaxDepth             int32       `protobuf:"zigzag32,4,opt,name=MaxDepth,proto3" json:"MaxDepth,omitempty"`
	Reference            []byte      `protobuf:"bytes,5,opt,name=Reference,proto3" json:"Reference,omitempty"`
	Options              *PinOptions `protobuf:"bytes,6,opt,name=Options,proto3" json:"Options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Pin) Reset()         { *m = Pin{} }
func (m *Pin) String() string { return proto.CompactTextString(m) }
func (*Pin) ProtoMessage()    {}
func (*Pin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Pin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pin.Unmarshal(m, b)
}
func (m *Pin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pin.Marshal(b, m, deterministic)
}
func (m *Pin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pin.Merge(m, src)
}
func (m *Pin) XXX_Size() int {
	return xxx_messageInfo_Pin.Size(m)
}
func (m *Pin) XXX_DiscardUnknown() {
	xxx_messageInfo_Pin.DiscardUnknown(m)
}

var xxx_messageInfo_Pin proto.InternalMessageInfo

func (m *Pin) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *Pin) GetType() Pin_PinType {
	if m != nil {
		return m.Type
	}
	return Pin_BadType
}

func (m *Pin) GetAllocations() [][]byte {
	if m != nil {
		return m.Allocations
	}
	return nil
}

func (m *Pin) GetMaxDepth() int32 {
	if m != nil {
		return m.MaxDepth
	}
	return 0
}

func (m *Pin) GetReference() []byte {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (m *Pin) GetOptions() *PinOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type PinOptions struct {
	ReplicationFactorMin int32             `protobuf:"zigzag32,1,opt,name=ReplicationFactorMin,proto3" json:"ReplicationFactorMin,omitempty"`
	ReplicationFactorMax int32             `protobuf:"zigzag32,2,opt,name=ReplicationFactorMax,proto3" json:"ReplicationFactorMax,omitempty"`
	Name                 string            `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ShardSize            uint64            `protobuf:"varint,4,opt,name=ShardSize,proto3" json:"ShardSize,omitempty"`
	UserAllocations      []string          `protobuf:"bytes,5,rep,name=UserAllocations,proto3" json:"UserAllocations,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PinOptions) Reset()         { *m = PinOptions{} }
func (m *PinOptions) String() string { return proto.CompactTextString(m) }
func (*PinOptions) ProtoMessage()    {}
func (*PinOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *PinOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PinOptions.Unmarshal(m, b)
}
func (m *PinOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PinOptions.Marshal(b, m, deterministic)
}
func (m *PinOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PinOptions.Merge(m, src)
}
func (m *PinOptions) XXX_Size() int {
	return xxx_messageInfo_PinOptions.Size(m)
}
func (m *PinOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PinOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PinOptions proto.InternalMessageInfo

func (m *PinOptions) GetReplicationFactorMin() int32 {
	if m != nil {
		return m.ReplicationFactorMin
	}
	return 0
}

func (m *PinOptions) GetReplicationFactorMax() int32 {
	if m != nil {
		return m.ReplicationFactorMax
	}
	return 0
}

func (m *PinOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PinOptions) GetShardSize() uint64 {
	if m != nil {
		return m.ShardSize
	}
	return 0
}

func (m *PinOptions) GetUserAllocations() []string {
	if m != nil {
		return m.UserAllocations
	}
	return nil
}

func (m *PinOptions) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.pb.Pin_PinType", Pin_PinType_name, Pin_PinType_value)
	proto.RegisterType((*Pin)(nil), "api.pb.Pin")
	proto.RegisterType((*PinOptions)(nil), "api.pb.PinOptions")
	proto.RegisterMapType((map[string]string)(nil), "api.pb.PinOptions.MetadataEntry")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x71, 0x9a, 0x6e, 0x26, 0xdd, 0x65, 0x77, 0xd8, 0x43, 0xb4, 0xe2, 0x60, 0xf5, 0x82,
	0x0f, 0x28, 0x87, 0x70, 0x41, 0xc0, 0xa5, 0xb4, 0xc0, 0xa9, 0x50, 0xb9, 0xf4, 0x07, 0xb8, 0xad,
	0x51, 0x2d, 0x42, 0x62, 0x25, 0x2e, 0x6a, 0xf8, 0x37, 0xfc, 0x1e, 0xfe, 0x14, 0xb2, 0xd3, 0x2f,
	0xd8, 0x1e, 0x22, 0xcd, 0x7b, 0x6f, 0x5e, 0x66, 0xf2, 0x32, 0x90, 0xd8, 0xd6, 0xa8, 0x26, 0x33,
	0x75, 0x65, 0x2b, 0x8c, 0xa4, 0xd1, 0x99, 0x59, 0x0e, 0x7f, 0x07, 0x40, 0x67, 0xba, 0xc4, 0x5b,
	0xa0, 0x63, 0xbd, 0x4e, 0x09, 0x23, 0x7c, 0x20, 0x5c, 0x89, 0x2f, 0x20, 0xfc, 0xda, 0x1a, 0x95,
	0x06, 0x8c, 0xf0, 0x9b, 0xfc, 0x59, 0xd6, 0x19, 0xb2, 0x99, 0x2e, 0xdd, 0xe3, 0x24, 0xe1, 0x1b,
	0x90, 0x41, 0x32, 0x2a, 0x8a, 0x6a, 0x25, 0xad, 0xae, 0xca, 0x26, 0xa5, 0x8c, 0xf2, 0x81, 0x38,
	0xa7, 0xf0, 0x01, 0xae, 0xa6, 0x72, 0x37, 0x51, 0xc6, 0x6e, 0xd2, 0x90, 0x11, 0x7e, 0x27, 0x8e,
	0x18, 0x9f, 0x43, 0x2c, 0xd4, 0x37, 0x55, 0xab, 0x72, 0xa5, 0xd2, 0x9e, 0x1f, 0x7f, 0x22, 0xf0,
	0x25, 0xf4, 0xbf, 0x98, 0xee, 0xbd, 0x11, 0x23, 0x3c, 0xc9, 0xf1, 0x6c, 0x8f, 0xbd, 0x22, 0x0e,
	0x2d, 0xc3, 0x05, 0xf4, 0xf7, 0xab, 0x61, 0x02, 0xfd, 0xf7, 0x72, 0xed, 0xca, 0xdb, 0x27, 0x38,
	0x80, 0xab, 0x89, 0xb4, 0xd2, 0x23, 0xe2, 0xd0, 0x54, 0xed, 0x51, 0x80, 0x08, 0x37, 0xe3, 0x62,
	0xdb, 0x58, 0x55, 0x4f, 0x46, 0x9f, 0x3c, 0x47, 0xf1, 0x1a, 0xe2, 0xf9, 0x46, 0xd6, 0x9d, 0x3d,
	0x1c, 0xfe, 0x09, 0x00, 0x4e, 0xe3, 0x30, 0x87, 0x7b, 0xa1, 0x4c, 0xa1, 0xbb, 0xaf, 0xfb, 0x28,
	0x57, 0xb6, 0xaa, 0xa7, 0xba, 0xf4, 0xd9, 0xdd, 0x89, 0x8b, 0xda, 0x65, 0x8f, 0xdc, 0xf9, 0x70,
	0x2f, 0x7a, 0xe4, 0x0e, 0x11, 0xc2, 0xcf, 0xf2, 0x87, 0x4a, 0x29, 0x23, 0x3c, 0x16, 0xbe, 0x76,
	0x69, 0xf9, 0xcd, 0xe6, 0xfa, 0x97, 0xf2, 0x51, 0x86, 0xe2, 0x44, 0x20, 0x87, 0xa7, 0x8b, 0x46,
	0xd5, 0xe7, 0x7f, 0xa3, 0xc7, 0x28, 0x8f, 0xc5, 0xff, 0x34, 0xbe, 0xeb, 0x32, 0x58, 0x4b, 0x2b,
	0xd3, 0x88, 0x51, 0x9e, 0xe4, 0xec, 0x71, 0xb0, 0xd9, 0xa1, 0xe5, 0x43, 0x69, 0xeb, 0x56, 0x1c,
	0x1d, 0x0f, 0x6f, 0xe1, 0xfa, 0x1f, 0xc9, 0x5d, 0xcf, 0x77, 0xd5, 0xfa, 0x04, 0x62, 0xe1, 0x4a,
	0xbc, 0x87, 0xde, 0x4f, 0x59, 0x6c, 0xbb, 0xf3, 0x89, 0x45, 0x07, 0xde, 0x04, 0xaf, 0xc9, 0x32,
	0xf2, 0x07, 0xf8, 0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x40, 0x89, 0x72, 0x8f, 0x02,
	0x00, 0x00,
}
