name: ipfs-cluster
version: git
summary: Collective pinning and composition for IPFS
description: |
  ipfs-cluster allows to replicate content (by pinning) in multiple IPFS nodes.

confinement: strict

apps:
  service:
    command: ipfs-cluster-service
    plugs: [home, network, network-bind]
    aliases: [ipfs-cluster-service]
  ctl:
    command: ipfs-cluster-ctl
    plugs: [network]
    aliases: [ipfs-cluster-ctl]

parts:
  ipfs-cluster:
    source: .
    plugin: nil
    build-packages: [make, wget]
    prepare: |
      mkdir -p ../go/src/github.com/ipfs/ipfs-cluster
      cp -R . ../go/src/github.com/ipfs/ipfs-cluster
    build: |
      env GOPATH=$(pwd)/../go CC=$SNAP_ARCH_TRIPLET-gcc CXX=$SNAP_ARCH_TRIPLET-g++ CGO_ENABLED=1 GOARCH=$TARGET_GOARCH make -C ../go/src/github.com/ipfs/ipfs-cluster install
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      for file in $(find ../go/bin/ -type f); do
          mv $file $SNAPCRAFT_PART_INSTALL/bin/
      done
    after: [go]
  go:
    source-tag: go1.11
