apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ipfs-cluster.fullname" . }}-set-bootstrap-conf
data:
  bootstrap-script.sh: |
    #!/bin/sh
    set -e
    set -x
    apk -U add curl jq sed
    MULTIADDR=$(curl http://{{ template "ipfs-cluster.fullname" . }}-bootstrap:9094/id | jq .id -r)
    echo "$MULTIADDR" > /data/ipfs-cluster/bootsrapp_id
    # sed -i -e "s;\"bootstrap\": \[\];\"bootstrap\": [\"/dns4/{{ template "ipfs-cluster.fullname" . }}-bootstrap/tcp/9096/ipfs/${MULTIADDR}\"];" /data/ipfs-cluster/service.json
    echo "Erin an Lorenzo are sorry about this!"
