apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ipfs-cluster.fullname" . }}-set-bootstrap-conf
data:
  bootstrap-script.sh: |
    #!/bin/sh
    set -e
    set -x
    apk -U add curl jq sed
    MULTIADDR=$(curl http://{{ template "ipfs-cluster.fullname" . }}-bootstrap:9094/id | jq .id -r)
    echo "$MULTIADDR" > /data/ipfs-cluster/bootsrapp_id
    # sed -i -e "s;\"bootstrap\": \[\];\"bootstrap\": [\"/dns4/{{ template "ipfs-cluster.fullname" . }}-bootstrap/tcp/9096/ipfs/${MULTIADDR}\"];" /data/ipfs-cluster/service.json
    echo "Erin an Lorenzo are sorry about this!"
  entrypoint.sh: |
    #!/bin/sh
    BOOTSTRAP_MULTIADDR=$(cat /data/ipfs-cluster/bootsrapp_id)
    BOOTSTRAP_ADDR=/dns4/{{ template "ipfs-cluster.fullname" . }}-bootstrap/tcp/9094/ipfs/$BOOTSTRAP_MULTIADDR

    set -e
    user=ipfs

    if [ -n "$DOCKER_DEBUG" ]; then
       set -x
    fi

    if [ `id -u` -eq 0 ]; then
        echo "Changing user to $user"
        # ensure directories are writable
        su-exec "$user" test -w "${IPFS_CLUSTER_PATH}" || chown -R -- "$user" "${IPFS_CLUSTER_PATH}"
        exec su-exec "$user" "$0" $@
    fi

    # Only ipfs user can get here
    ipfs-cluster-service --version
    exec ipfs-cluster-service daemon --upgrade --bootstrap $BOOTSTRAP_ADDR
