apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hera-instances.fullname" . }}-env
  labels:
    app: {{ template "hera-instances.name" . }}
    chart: {{ template "hera-instances.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end -}}
